const siteMetadata = {
  title: 'Jeff Maxwell Developer Portfolio',
  description: `Jeff Maxwell's developer portfolio made with Gatsby`,
  author: 'Jeff Maxwell',
  createdAt: 2019 - 2025,
  siteUrl: 'https://www.el-jefe.me',
};

module.exports = {
  siteMetadata,
  // eslint-disable-next-line prettier/prettier
  adapter: require(`gatsby-adapter-netlify`).default({ // eslint-disable-line global-require
    excludeDatastoreFromEngineFunction: false,
    imageCDN: false,
  }),
  plugins: [
    `gatsby-plugin-webpack-bundle-analyser-v2`,
    `gatsby-plugin-react-helmet-async`,
    `gatsby-plugin-image`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    {
      resolve: `gatsby-plugin-sharp`,
      options: {
        defaults: {
          formats: [`auto`, `webp`, `avif`],
          placeholder: `blurred`,
          quality: 85,
          breakpoints: [750, 1080, 1366, 1920],
          backgroundColor: `transparent`,
          tracedSVGOptions: {},
          blurredOptions: {},
          jpgOptions: {},
          pngOptions: {},
          webpOptions: {
            quality: 85,
          },
          avifOptions: {
            quality: 80,
          },
        },
      },
    },
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `Jeff Maxwell - Full Stack Developer Portfolio`,
        short_name: `Jeff Maxwell`,
        description: `Jeff Maxwell's professional developer portfolio showcasing React, Node.js, and modern web development projects`,
        start_url: `/`,
        background_color: `#052f5f`,
        theme_color: `#fc4a1a`,
        display: `standalone`,
        orientation: `portrait-primary`,
        icon: 'src/images/elephant_noun_project.png',
        icon_options: {
          purpose: `any maskable`,
        },
        include_favicon: true,
        legacy: true,
        categories: ['developer-tools', 'portfolio', 'productivity'],
        lang: 'en',
        dir: 'ltr',
        prefer_related_applications: false,
        crossOrigin: 'use-credentials',
        cache_busting_mode: 'none',
      },
    },
    {
      resolve: `gatsby-plugin-preconnect`,
      options: {
        domains: ['https://fonts.googleapis.com', 'https://fonts.gstatic.com'],
      },
    },
    {
      resolve: `gatsby-plugin-emotion`,
    },
    {
      resolve: `gatsby-plugin-web-font-loader`,
      options: {
        custom: {
          families: [
            'AvenirLTStd-Roman',
            'HelveticaNeueLTStd-Bd',
            'HelveticaNeueLTStd-Roman',
            'SabonLTStd-Roman',
          ],
          urls: ['/fonts/fonts.css'],
        },
      },
    },
    {
      resolve: `gatsby-plugin-sitemap`,
      options: {
        excludes: [],
        query: `
          {
            allSitePage {
              nodes {
                path
              }
            }
          }
        `,
        resolveSiteUrl: () => siteMetadata.siteUrl,
        serialize: ({ path, modifiedGmt }) => {
          return {
            url: path,
            lastmod: modifiedGmt,
          };
        },
      },
    },
    {
      resolve: `gatsby-plugin-html-minifier`,
      options: {
        caseSensitive: true,
        collapseBooleanAttributes: true,
        collapseInlineTagWhitespace: true,
        collapseWhitespace: true,
        conservativeCollapse: false,
        continueOnParseError: false,
        customAttrAssign: [],
        customAttrCollapse: '',
        customAttrSurround: [],
        customEventAttributes: [],
        decodeEntities: true,
        html5: true,
        ignoreCustomComments: [],
        ignoreCustomFragments: [],
        includeAutoGeneratedTags: false,
        keepClosingSlash: false,
        maxLineLength: 0,
        minifyCSS: true,
        minifyJS: true,
        minifyURLs: true,
        preserveLineBreaks: false,
        preventAttributesEscaping: false,
        processConditionalComments: true,
        processScripts: ['text/html'],
        quoteCharacter: '"',
        removeAttributeQuotes: true,
        removeComments: true,
        removeEmptyAttributes: true,
        removeEmptyElements: false,
        removeOptionalTags: false,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true,
        removeTagWhitespace: true,
        sortAttributes: true,
        sortClassName: true,
        trimCustomFragments: true,
        useShortDoctype: true,
      },
    },
    // gatsby-plugin-netlify must be last in the plugins array
    `gatsby-plugin-netlify`,
  ],
};
